name: prod
color: "#B83D7F"
variables:
  - name: host
    value: https://clickprintbackend.wckd.pk
  - secret: true
    name: token
  - secret: true
    name: number
  - secret: true
    name: SERVICE_KEY
