name: prod
color: "#B83D7F"
variables:
  - name: host
    value: https://api.clickprint.pk
  - secret: true
    name: token
    description: ""
  - secret: true
    name: number
    description: ""
  - secret: true
    name: fileId
    description: ""
